name: Run Tests

on: push

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm run test:cov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          #files: ./coverage/lcov.info
          token: ${{ secrets.TP01_TESTESSOFTWARE }}
          flags: unittests
          name: olisaude-backend-coverage
          verbose: true

 
    
